// Generated by CoffeeScript 1.3.3
(function() {
  var Scouter, root;

  Scouter = (function() {

    function Scouter() {}

    Scouter.prototype.score = function(str) {
      var a, b, c, score, selectors;
      selectors = this.parse(str);
      a = selectors.filter(function(element) {
        return element.indexOf('#') !== -1;
      });
      b = selectors.filter(function(element) {
        var _ref;
        return ((_ref = element.match(/\[.+\]|\.[_a-zA-Z0-9-]|:[_a-zA-Z0-9-]/)) != null ? _ref.length : void 0) && element.indexOf('::') === -1;
      });
      selectors = selectors.filter(function(i) {
        return !(a.concat(b).indexOf(i) > -1);
      });
      c = selectors;
      score = parseInt("" + a.length + b.length + c.length, 10);
      return score;
    };

    Scouter.prototype.parse = function(str) {
      var match, matches, selector, selectors, _i, _j, _len, _len1, _ref;
      selectors = [];
      _ref = str.split(/[\s,+~>]+/);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        selector = _ref[_i];
        matches = selector.match(/\[.+\]|#[_a-zA-Z0-9-]*|\.[_a-zA-Z0-9-]*|::[_a-zA-Z0-9-]*|:[_a-zA-Z0-9-]*|[_a-zA-Z0-9-]*/gi);
        if (matches) {
          for (_j = 0, _len1 = matches.length; _j < _len1; _j++) {
            match = matches[_j];
            match = match.replace(/:not|\(|\)/ig, '');
            if (match.length) {
              selectors.push(match);
            }
          }
        } else {
          selectors.push(selector);
        }
      }
      return selectors;
    };

    Scouter.prototype.sort = function(selectors, order) {
      var _this = this;
      if (order == null) {
        order = 'desc';
      }
      if (order === 'desc') {
        selectors.sort(function(a, b) {
          return _this.score(b) - _this.score(a);
        });
      } else {
        selectors.sort(function(a, b) {
          return _this.score(a) - _this.score(b);
        });
      }
      return selectors;
    };

    return Scouter;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Scouter = Scouter;

}).call(this);
